In [1]:
import altair_express as alx
from vega_datasets import data
import altair as alt

import pandas as pd

In [2]:
#(alx.highlight_brush()+alx.stripplot(data=data.movies(),x="IMDB_Rating",color='Major_Genre',row='Major_Genre'))

In [3]:
df = data.seattle_temps()

df['month'] = pd.DatetimeIndex(df['date']).month_name()
df['month_index'] = pd.DatetimeIndex(df['date']).month

df

                    date  temp     month  month_index
0    2010-01-01 00:00:00  39.4   January            1
1    2010-01-01 01:00:00  39.2   January            1
2    2010-01-01 02:00:00  39.0   January            1
3    2010-01-01 03:00:00  38.9   January            1
4    2010-01-01 04:00:00  38.8   January            1
...                  ...   ...       ...          ...
8754 2010-12-31 19:00:00  40.7  December           12
8755 2010-12-31 20:00:00  40.5  December           12
8756 2010-12-31 21:00:00  40.2  December           12
8757 2010-12-31 22:00:00  40.0  December           12
8758 2010-12-31 23:00:00  39.6  December           12

[8759 rows x 4 columns]

In [22]:
alx.highlight_color()+(alx.highlight_brush()+alx.stripplot(df.sample(5000),width=400,x='temp',color='month', row='month_index')).configure_facet(
    spacing=0
).configure_view(
    stroke=None
)

is x meaningful?  True
is y meaningful?  False
<class 'altair.vegalite.v5.api.Chart'>
<class 'altair.vegalite.v5.api.FacetChart'>
True

SchemaValidationError: Invalid specification

        altair.vegalite.v5.schema.core.PointSelectionConfig->fields->items, validating 'type'

        None is not of type 'string'

In [108]:
df = pd.read_csv('https://gist.githubusercontent.com/dwootton/7abdfb610843b745ece01c9ae03f50e4/raw/840f18415c465bec37443e8d2812eb0eb6894013/censuspop.csv')
alx.barplot(df,x='Age',y='People',column='Year').resolve_scale(y='independent')

alt.FacetChart(...)

In [109]:
alx.highlight_color()+alt.Chart(df).transform_window(
    cumulative_pop='sum(People)',sort=[{'field': 'Age'}],groupby=['Year']
).mark_line().encode(
    x='Age',color='Year:N',y='cumulative_pop:Q'
)

alt.LayerChart(...)

In [266]:

df.groupby('Year').

In [110]:
df.groupby(['Age','Year']).aggregate('sum').reset_index()

    Age  Year  Sex    People
0     0  1900    3   9208740
1     0  2000    3  19046094
2     5  1900    3   8856266
3     5  2000    3  20621710
4    10  1900    3   8059418
5    10  2000    3  20585757
6    15  1900    3   7576589
7    15  2000    3  19930088
8    20  1900    3   7445099
9    20  2000    3  19055559
10   25  1900    3   6625336
11   25  2000    3  19178000
12   30  1900    3   5584138
13   30  2000    3  20325175
14   35  1900    3   4981620
15   35  2000    3  23110829
16   40  1900    3   4266057
17   40  2000    3  22808830
18   45  1900    3   3516438
19   45  2000    3  20186259
20   50  1900    3   2983019
21   50  2000    3  17419067
22   55  1900    3   2226540
23   55  2000    3  13380350
24   60  1900    3   1804079
25   60  2000    3  10792360
26   65  1900    3   1312875
27   65  2000    3   9258407
28   70  1900    3    894754
29   70  2000    3   8977000
30   75  1900    3    534090
31   75  2000    3   7268299
32   80  1900    3    259884
33   80  2000    3   5124536
34   85  1900    3     92622
35   85  2000    3   2951513
36   90  1900    3     35257
37   90  2000    3   1400884

In [262]:
df = df.groupby(['Age','Year']).aggregate('sum').reset_index()

# calculate cumsum of Pop
df['no_csum'] = df.groupby(['Year'])['People'].cumsum()

/var/folders/p0/6drk3lgs5lsdshny3wjmg53m0000gn/T/ipykernel_13197/3937509350.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df = df.groupby(['Age','Year']).aggregate('sum').reset_index()

In [120]:
df
column = 'no_csum'

df['norm'] = df.groupby('Year')['no_csum'].transform(lambda x: (x) / x.max())

In [146]:
df['people_per_hundred']=df.groupby('Year')['People'].apply(lambda x:round(100 * x / float(x.sum())))

/var/folders/p0/6drk3lgs5lsdshny3wjmg53m0000gn/T/ipykernel_13197/3258515635.py:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  df['people_per_hundred']=df.groupby('Year')['People'].apply(lambda x:round(100 * x / float(x.sum())))

In [150]:
 

exploded = df.loc[df.index.repeat(df.people_per_hundred)]
exploded

    Age  Year  Sex   People    no_csum      norm  norm_pop  people_per_hundred
0     0  1900    3  9208740    9208740  0.120750  1.000000                12.0
0     0  1900    3  9208740    9208740  0.120750  1.000000                12.0
0     0  1900    3  9208740    9208740  0.120750  1.000000                12.0
0     0  1900    3  9208740    9208740  0.120750  1.000000                12.0
0     0  1900    3  9208740    9208740  0.120750  1.000000                12.0
..  ...   ...  ...      ...        ...       ...       ...                 ...
31   75  2000    3  7268299  271943784  0.966325  0.314498                 3.0
31   75  2000    3  7268299  271943784  0.966325  0.314498                 3.0
33   80  2000    3  5124536  277068320  0.984534  0.221737                 2.0
33   80  2000    3  5124536  277068320  0.984534  0.221737                 2.0
35   85  2000    3  2951513  280019833  0.995022  0.127711                 1.0

[201 rows x 8 columns]

In [170]:
alt.Chart(exploded[exploded['Year']==2000]).mark_circle(opacity=1,size=125,color='lightgray').transform_window(
    id='rank()',
    groupby=['Age']
).encode(
    alt.X('Age:O'),
    alt.Y('id:O',
          axis=None,
          sort='descending')
).properties(height=100).configure_view(
    strokeWidth=0
)

alt.Chart(...)

In [171]:
alt.Chart(exploded[exploded['Year']==1900]).mark_circle(opacity=1,size=125,color='lightgray').transform_window(
    id='rank()',
    groupby=['Age']
).encode(
    alt.X('Age:O'),
    alt.Y('id:O',
          axis=None,
          sort='descending')
).properties(height=150).configure_view(
    strokeWidth=0
)

alt.Chart(...)

In [129]:
alx.pan_zoom()+alt.Chart(df).mark_line().encode(
    x='Age',color=alt.Color('Year:N',scale=alt.Scale(domain=[1900,2000],range=["gray","black"])),y='norm:Q'
).configure_view(strokeWidth=0).configure_axis(grid=False, domain=False)

alt.Chart(...)

In [196]:
mapping = {
    0:'0-20',
    5:'0-20',
    10:'0-20',
    15:'0-20',
    20:'0-20',
    25:'25-40',
    30:'25-40',
    35:'25-40',
    40:'25-40',
    45:'45-60',
    50:'45-60',
    55:'45-60',
    60:'45-60',
    65:'65-90',
    70:'65-90',
    75:'65-90',
    80:'65-90',
    85:'65-90', 
    90:'65-90', 
}

df["grouped_age"] = df["Age"].map(mapping)

In [204]:

new_df = df.groupby(['grouped_age','Year']).mean().reset_index()

alt.Chart(new_df).mark_line().encode(x='Year:O',y='People',color='grouped_age').properties(width=

alt.Chart(...)

In [209]:
new_df

,grouped_age,Year,Age,Sex,People,no_csum,norm,norm_pop,people_per_hundred
0,0-20,1900,10.0,3.0,8.229222e+06,2.564906e+07,0.336325,0.893632,11.000000
1,0-20,2000,10.0,3.0,1.984784e+07,5.967806e+07,0.212060,0.858811,7.000000
2,25-40,1900,32.5,3.0,5.364288e+06,5.551688e+07,0.727968,0.582521,7.250000
3,25-40,2000,32.5,3.0,2.135571e+07,1.509187e+08,0.536274,0.924056,7.500000
4,45-60,1900,52.5,3.0,2.632519e+06,6.992126e+07,0.916846,0.285872,3.500000
5,45-60,2000,52.5,3.0,1.544451e+07,2.273009e+08,0.807691,0.668280,5.500000
6,65-90,1900,77.5,3.0,5.215803e+05,7.571459e+07,0.992811,0.056640,0.666667
7,65-90,2000,77.5,3.0,5.830106e+06,2.718044e+08,0.965830,0.252267,2.000000

In [212]:
new_df['normed_pop'] = new_df.groupby('Year')['People'].transform(lambda x: (x) / x.sum())

In [217]:
alt.Chart(new_df).mark_line().encode(x='Year:O',y='normed_pop',color='grouped_age').properties(width=150).configure_view(strokeWidth=0).configure_axis(grid=False, domain=False)

alt.Chart(...)

In [218]:
new_df

,grouped_age,Year,Age,Sex,People,no_csum,norm,norm_pop,people_per_hundred,normed_pop
0,0-20,1900,10.0,3.0,8.229222e+06,2.564906e+07,0.336325,0.893632,11.000000,0.491367
1,0-20,2000,10.0,3.0,1.984784e+07,5.967806e+07,0.212060,0.858811,7.000000,0.317676
2,25-40,1900,32.5,3.0,5.364288e+06,5.551688e+07,0.727968,0.582521,7.250000,0.320302
3,25-40,2000,32.5,3.0,2.135571e+07,1.509187e+08,0.536274,0.924056,7.500000,0.341811
4,45-60,1900,52.5,3.0,2.632519e+06,6.992126e+07,0.916846,0.285872,3.500000,0.157188
5,45-60,2000,52.5,3.0,1.544451e+07,2.273009e+08,0.807691,0.668280,5.500000,0.247199
6,65-90,1900,77.5,3.0,5.215803e+05,7.571459e+07,0.992811,0.056640,0.666667,0.031144
7,65-90,2000,77.5,3.0,5.830106e+06,2.718044e+08,0.965830,0.252267,2.000000,0.093314

In [219]:
new_df

,grouped_age,Year,Age,Sex,People,no_csum,norm,norm_pop,people_per_hundred,normed_pop
0,0-20,1900,10.0,3.0,8.229222e+06,2.564906e+07,0.336325,0.893632,11.000000,0.491367
1,0-20,2000,10.0,3.0,1.984784e+07,5.967806e+07,0.212060,0.858811,7.000000,0.317676
2,25-40,1900,32.5,3.0,5.364288e+06,5.551688e+07,0.727968,0.582521,7.250000,0.320302
3,25-40,2000,32.5,3.0,2.135571e+07,1.509187e+08,0.536274,0.924056,7.500000,0.341811
4,45-60,1900,52.5,3.0,2.632519e+06,6.992126e+07,0.916846,0.285872,3.500000,0.157188
5,45-60,2000,52.5,3.0,1.544451e+07,2.273009e+08,0.807691,0.668280,5.500000,0.247199
6,65-90,1900,77.5,3.0,5.215803e+05,7.571459e+07,0.992811,0.056640,0.666667,0.031144
7,65-90,2000,77.5,3.0,5.830106e+06,2.718044e+08,0.965830,0.252267,2.000000,0.093314

In [222]:
pd.DataFrame(df[df['Year']==1900])

,Age,Year,Sex,People,no_csum,norm,norm_pop,people_per_hundred,grouped_age
0,0,1900,3,9208740,9208740,0.120750,1.000000,12.0,0-20
2,5,1900,3,8856266,18065006,0.236878,0.961724,12.0,0-20
4,10,1900,3,8059418,26124424,0.342558,0.875192,11.0,0-20
6,15,1900,3,7576589,33701013,0.441906,0.822761,10.0,0-20
8,20,1900,3,7445099,41146112,0.539530,0.808482,10.0,0-20
10,25,1900,3,6625336,47771448,0.626405,0.719462,9.0,25-40
12,30,1900,3,5584138,53355586,0.699628,0.606395,7.0,25-40
14,35,1900,3,4981620,58337206,0.764949,0.540967,7.0,25-40
16,40,1900,3,4266057,62603263,0.820888,0.463262,6.0,25-40
18,45,1900,3,3516438,66119701,0.866998,0.381859,5.0,45-60
20,50,1900,3,2983019,69102720,0.906113,0.323933,4.0,45-60
22,55,1900,3,2226540,71329260,0.935308,0.241786,3.0,45-60
24,60,1900,3,1804079,73133339,0.958965,0.195909,2.0,45-60
26,65,1900,3,1312875,74446214,0.976180,0.142568,2.0,65-90
28,70,1900,3,894754,75340968,0.987912,0.097164,1.0,65-90
30,75,1900,3,534090,75875058,0.994915,0.057998,1.0,65-90
32,80,1900,3,259884,76134942,0.998323,0.028221,0.0,65-90
34,85,1900,3,92622,76227564,0.999538,0.010058,0.0,65-90
36,90,1900,3,35257,76262821,1.000000,0.003829,0.0,65-90

In [231]:
months = [1,2,3,4,5,6,7,8,9,10,11,12]
base_df = df[df['Year']==1900].copy(deep=True)
all_df = []

for month in months:
    month_df = base_df.copy(deep=True)
    month_df['month'] = month
    print(len(all_df))
    all_df.append(month_df)
    
pd.concat(all_df)

0
1
2
3
4
5
6
7
8
9
10
11

0      1
2      1
4      1
6      1
8      1
      ..
28    12
30    12
32    12
34    12
36    12
Name: month, Length: 228, dtype: int64

In [233]:
pd.concat(all_df)

,Age,Year,Sex,People,no_csum,norm,norm_pop,people_per_hundred,grouped_age,month
0,0,1900,3,9208740,9208740,0.120750,1.000000,12.0,0-20,1
2,5,1900,3,8856266,18065006,0.236878,0.961724,12.0,0-20,1
4,10,1900,3,8059418,26124424,0.342558,0.875192,11.0,0-20,1
6,15,1900,3,7576589,33701013,0.441906,0.822761,10.0,0-20,1
8,20,1900,3,7445099,41146112,0.539530,0.808482,10.0,0-20,1
...,...,...,...,...,...,...,...,...,...,...
28,70,1900,3,894754,75340968,0.987912,0.097164,1.0,65-90,12
30,75,1900,3,534090,75875058,0.994915,0.057998,1.0,65-90,12
32,80,1900,3,259884,76134942,0.998323,0.028221,0.0,65-90,12
34,85,1900,3,92622,76227564,0.999538,0.010058,0.0,65-90,12
36,90,1900,3,35257,76262821,1.000000,0.003829,0.0,65-90,12

In [250]:
copy = df[df['Year']==1900].copy(deep=True)

aged_copy = pd.concat([copy,copy,copy,copy,copy]).sort_values('Age').reset_index().reset_index()#.to_csv('1900_pop.csv')

In [251]:
copy = df[df['Year']==1900].copy(deep=True)

In [253]:
months = [1,2,3,4,5,6,7,8,9,10,11,12]
base_df = aged_copy.copy(deep=True)
all_df = []

for month in months:
    month_df = base_df.copy(deep=True)
    month_df['month'] = month
    print(len(all_df))
    all_df.append(month_df)
    
for_export = pd.concat(all_df)

0
1
2
3
4
5
6
7
8
9
10
11

In [257]:
for_export.rename({"level_0":"Individual_Age"},axis=1).to_csv('1900_pop_2.csv')

In [260]:
k2_copy = df[df['Year']==2000].copy(deep=True)

aged_copy = pd.concat([k2_copy,k2_copy,k2_copy,k2_copy,k2_copy]).sort_values('Age').reset_index().reset_index()#.to_csv('1900_pop.csv')


months = [1,2,3,4,5,6,7,8,9,10,11,12]
base_df = aged_copy.copy(deep=True)
all_df = []

for month in months:
    month_df = base_df.copy(deep=True)
    month_df['month'] = month
    all_df.append(month_df)
    
for_export = pd.concat(all_df)
for_export.rename({"level_0":"Individual_Age"},axis=1).to_csv('2000_pop_2.csv')

In [261]:
for_export

,level_0,index,Age,Year,Sex,People,no_csum,norm,norm_pop,people_per_hundred,grouped_age,month
0,0,1,0,2000,3,19046094,19046094,0.067678,0.824120,7.0,0-20,1
1,1,1,0,2000,3,19046094,19046094,0.067678,0.824120,7.0,0-20,1
2,2,1,0,2000,3,19046094,19046094,0.067678,0.824120,7.0,0-20,1
3,3,1,0,2000,3,19046094,19046094,0.067678,0.824120,7.0,0-20,1
4,4,1,0,2000,3,19046094,19046094,0.067678,0.824120,7.0,0-20,1
...,...,...,...,...,...,...,...,...,...,...,...,...
90,90,37,90,2000,3,1400884,281420717,1.000000,0.060616,0.0,65-90,12
91,91,37,90,2000,3,1400884,281420717,1.000000,0.060616,0.0,65-90,12
92,92,37,90,2000,3,1400884,281420717,1.000000,0.060616,0.0,65-90,12
93,93,37,90,2000,3,1400884,281420717,1.000000,0.060616,0.0,65-90,12
94,94,37,90,2000,3,1400884,281420717,1.000000,0.060616,0.0,65-90,12